apiVersion: v1
kind: Secret
metadata:
  name: unencrypted-secret
  namespace: default
  labels:
    app: my-app
  annotations:
    # Notice: NO "def.ms/sops-encrypt: true" annotation
    description: "This secret will NOT be encrypted (missing annotation)"
type: Opaque
stringData:
  public-config: "This data is not sensitive and remains unencrypted in Git"
  non-secret-value: "visible-in-repository"
  feature-flag: "enabled"
